### ISSUE TITLE
Create a Smart Contract that Issues ERC 721 Tokens

### ISSUE THREAD

**Issue by thebkr7** [BountyOneBounties/Issues#6]
Create a Smart Contract that issues ERC 721 tokens to addresses specified by the owner.

Requirments:
These tokens are not transferable.
Each token can have a string attached as metadata that is publicly retrievable.
Burning functionality by only owner.

**Comment by hnamzian** [comment]
This is the repository for this contract.
https://github.com/hnamzian/ERC721Bounty
email:namazian87@gmail.com
ETH: 0xB3EeCE8b0d3a389Fd182e46Ef55B3a6E270cFB17

**Comment by thebkr7** [comment]
@hnamzian Thank you. It is under review

**Comment by nflaig** [comment]
Hey @thebkr7 , 
the Smart Contract for this bounty (#6) is here:
https://github.com/nflaig/token/tree/master/contracts/ERC721/token-distribution

Email: nflaig@protonmail.com
ETH-Address: `0x5043ABB65c3230fE47a85F2ede23fB67E498a881`

**Comment by thebkr7** [comment]
@hnamzian You have been awarded.

**Comment by nflaig** [comment]
Hey @thebkr7 ,
I saw you forked my repository aswell. Would you mind giving me a short feedback if my solution was valid aswell for your requirements, would help me alot. Also i looked into the first submitted solution and i don't really understand how it is a good solution for this task since it has atleast 10 things which are not needed and also is a 1 to 1 copy of the OpenZepplin repository just not forked but copied and uploaded (shouldnt the MIT License be mentioned? or how does this work?). https://github.com/OpenZeppelin/openzeppelin-solidity/tree/master/contracts/token/ERC721

I really dont care who gets the bounty it is all about learning for me therefore a feedback would be highly appreciated :)

**Comment by hnamzian** [comment]
@nflaig the OpenZeppelin codes are well audited and I think  it's better to use them rather than reinventing again and again. As you see I didn't hide or clean the comments of those code and everyone can realize the developers of the code.

**Comment by nflaig** [comment]
@hnamzian Thanks for the response :)
I thought you have to mention from where you got the code if you don't fork it, good to know. But what I don't understand is why you need all the mappings for approvals if the tokens are not transferable. Shouldn't the functions of the ERC721 Interface that you don't explicitly need because your contract doesn't use them just `revert()` or throw an error (`event`). For example, the `approve()` function sets approvals in the mapping `tokenApprovals` for `_tokenId` to an address `_to`. My question here is why do you need the mapping for non transferable tokens and wouldn't it be better if the function throws an error to inform the user that this ERC721 does not use this functionality. As I understand it, contracts should be as simple as possible which saves Gas and is a lot more transparent for an outsider who wants to check the code to verify the functionality of the contract in a short time. Maybe I am wrong here and this was the simplest and most efficient way to solve this Problem (#6). Looking forward to hearing your opinion on that :)

**Comment by hnamzian** [comment]
@nflaig You are right I should have mentioned the source too.
However I tried to provide more functionality in which the owner also can set transferable any whitelisted address and then that address can be transferred the reward. Here it seems we don't need such functions but I that was my thought that it can help the project in future.

**Comment by nflaig** [comment]
@hnamzian Thanks for clarification

**Comment by thebkr7** [comment]
@nflaig Sorry for the delay. I will take a look at your code today again. I briefly looked a while ago but since @hnamzian was first and it met the basic req we accepted it.
As for copying Zepplin, it is nearly a standard to use their code. Yes it would have been good to give them credit though.
We are working getting the details finished for a much bigger solidity job that we will be posting at the end of this or next week. I hope you both can work on it as there will be multiple sections to it.
